// frontend/src/routes/bus/[id]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { PageData } from './$houdini'
	import * as maplibregl from 'maplibre-gl'

	export let data: PageData
	$: ({ BusInfo } = data)

	$: bus = $BusInfo.data?.bus
	$: route = bus?.route && JSON.parse(bus?.route)

	let div: HTMLElement
	let map: maplibregl.Map | null = null

	onMount(() => {
		map = new maplibregl.Map({
			container: div,
			style: "https://tiles.stadiamaps.com/styles/alidade_smooth.json",
			zoom: 15
		})

		return () => {
			map?.remove()
		}
	})

	$: coordinates = route && route.features[0].geometry.coordinates
	$: bounds = coordinates ? new maplibregl.LngLatBounds({
		lat: coordinates[0][0],
		lng: coordinates[0][1]
	}) : null
	$: {
		 if (coordinates)  {
				for (let coordinate of coordinates) {
					bounds?.extend(coordinate)
				}
		}
	}

	function recenter() {
		if (bounds && map) {
			map?.fitBounds(bounds, {
				padding: 20,
				animate: false
			})
		}
	}

	let loaded = false
	$: map?.on('load', () => {
		loaded = true
	})
	$: {
		if (loaded) {
			if (map?.getSource('route')) {
				map?.removeSource('route');
			}
			map?.addSource('route', {
				type: 'geojson',
				data: route
			})
			map?.addLayer({
				id: 'route',
				type: 'line',
				source: 'route',
				'layout': {
					'line-join': 'round',
					'line-cap': 'round'
				},
				'paint': {
					'line-color': "#000",
					'line-width': 8
				}
			})
			recenter()
		}
	}

</script>

<h1 class="text-5xl mb-5 font-bold">{bus?.name}</h1>
{#if bus?.description}
	<p class="text-xl">{bus?.description}</p>
{/if}

<div bind:this={div} />

<style>
	div {
		max-height: 70vh;
		height: 70vh;
	}
</style>

// front/src/pages/bus/[id].tsx
import { client } from "@/lib/urql";
import { Link, Params, useParams } from "@/router";
import { graphql } from "@/gql/gql";
import { useQuery } from "urql";
import { useMemo } from "preact/hooks";
import Map, { Layer, Source } from "react-map-gl/maplibre";
import { LngLatBounds } from "maplibre-gl";

const ShowBus = graphql(`
  query ShowBus($id: ID!) {
    bus(id: $id) {
      id
      name
      description
      route
    }
  }
`);

export const Loader = ({ params }: { params: Params["/bus/:id"] }) => {
  const { id } = params;
  return client.query(ShowBus, { id }).toPromise;
};

function Route(props: { route?: string }) {
  const parsedJson = useMemo(() => {
    if (props.route) {
      try {
        return JSON.parse(props.route);
      } catch (e) {
        return null;
      }
    }
    return null;
  }, [props.route]);

  return (
    <Source type="geojson" data={parsedJson}>
      <Layer
        type="line"
        layout={{
          "line-join": "round",
          "line-cap": "round",
        }}
        paint={{
          "line-color": "#000",
          "line-width": 8,
        }}
      />
    </Source>
  );
}

export default function ShowBusPage() {
  const { id } = useParams("/bus/:id");
  const [{ data, fetching }] = useQuery({
    query: ShowBus,
    variables: {
      id,
    },
  });

  if (fetching || !data?.bus) {
    return <h1>Loading...</h1>;
  }

  const parsedJson = useMemo(() => {
    if (data.bus?.route) {
      try {
        return JSON.parse(data.bus.route);
      } catch (e) {
        return null;
      }
    }
    return null;
  }, [data.bus.route]);

  const coordinates = parsedJson && parsedJson.features[0].geometry.coordinates;

  const bounds = useMemo(() => {
    if (coordinates) {
      const latlngbound = new LngLatBounds({
        lat: coordinates[0][0],
        lng: coordinates[0][1],
      });
      for (let coordinate of coordinates) {
        latlngbound.extend(coordinate);
      }
      return latlngbound;
    }
  }, [coordinates]);

  return (
    <div>
      <p class="text-2xl mb-4">
        <Link to="/">Bike Bus</Link>
      </p>
      <h1 class="text-4xl font-bold mb-8">{data.bus.name}</h1>
      <p>{data.bus.description}</p>
      <Map
        style={{
          width: "100%",
          height: "60vh",
        }}
        initialViewState={{
          bounds: bounds,
          zoom: 14,
          fitBoundsOptions: {
            padding: 20,
          },
        }}
        mapStyle="https://tiles.stadiamaps.com/styles/alidade_smooth.json"
      >
        <Route route={data.bus.route} />
      </Map>
    </div>
  );
}
